/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/goose-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Plane_Material003_0.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane_Material003_0_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_Material003_0_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/goose-transformed.glb')
